Make NumPy available:

In [ ]:
#Install latest version of pip
!pip install --upgrade pip

#Increase speed using numba library
!pip -q install numba # -q is for quiet mode
import numba

Requirement already up-to-date: pip in /home/nbuser/anaconda3_420/lib/python3.5/site-packages (19.3.1)


In [ ]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [ ]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

#### (1) Add two vectors using built-in addition operator:

In [ ]:
# YOUR CODE HERE
x = np.random.rand(int(1e4))
y = np.random.rand(int(1e4))

%time z_1 = x + y

#### (2) Add two vectors using own implementation:

In [ ]:
# YOUR CODE HERE

def add_vector(x,y):
    z_2 = np.zeros(len(x))
    for i in range(len(x)):
        z_2[i] = x[i] + y[i]
    
%time add_vector(x,y)
        

In [ ]:
#Increase speed using numba library
#!pip -q install numba # -q is for quiet mode
#import numba

@numba.jit
def add_vector_jit(x,y):
    z_3 = np.zeros(len(x))
    for i in range(len(x)):
        z_3[i] = x[i] + y[i]


%time add_vector_jit(x,y) # Need to call once to complete the compilation step
%time add_vector_jit(x,y)

### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [7]:
!pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

CPU times: user 22.8 s, sys: 29.6 s, total: 52.4 s
Wall time: 1min 10s
CPU times: user 1.01 s, sys: 2.1 s, total: 3.1 s
Wall time: 3.52 s


**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [8]:
def to_percentage_and_sort(scores):
    # YOUR CODE HERE
    scores *= (100/60)
    scores.sort()
    return scores

def statistics(scores, exclude=False):
    # YOUR CODE HERE
    score_data = {"min": None, "max": None, "mean": None}
    if exclude == False:
        scores /= (100/60) # Return scores back to raw
        pass
    else:
        #Remove the max entry and the min entry
        scores.sort()
        scores = np.delete(scores, len(scores) - 1) #Remove highest element
        scores = np.delete(scores, 0) #Remove lowest element

    score_data["min"] = scores.min()
    score_data["max"] = scores.max()
    score_data["mean"] = scores.mean()
    return score_data

In [9]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [10]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [11]:
# YOUR CODE HERE
print(A[:,2])

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [12]:
# YOUR CODE HERE
print(A[:2])

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [13]:
# YOUR CODE HERE
print(A[-2:,-2:])

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [14]:
# YOUR CODE HERE
print(np.sum(A[:,-1]))

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [15]:
# YOUR CODE HERE
print(A.T)

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [16]:
#@numba.jit #Slows down with numba.jit???
def my_f(x):
    "Evaluate polynomial function"
    return x**3 - 6*x**2 + 4*x + 12

In [17]:
from scipy import optimize

%time optimize.bisect(f=my_f, a=3, b=6, xtol=1.0e-6, maxiter=1000)

CPU times: user 15 µs, sys: 31 µs, total: 46 µs
Wall time: 51.7 µs


4.534069776535034

In [18]:
#@numba.jit #Doesn't WORK??
def compute_root(f, x0, x1, tol, max_it):
    "Compute roots of a function using bisection"
    it = 0
    error = tol + 1. #Set error to be greater than the tolerance
    
    while error > tol and it < max_it:
        #Increment counter
        it += 1
        
        #Get mid val
        x_mid = (x0 + x1)/2
        
        #Compute f(x0) and f(x_mid)
        f0 = f(x0)
        f_mid = f(x_mid)
        
        #Get the sign
        sign = f0 * f_mid
        
        if sign < 0: #Negative, so move x1 to x_mid
            x1 = x_mid
        else:
            x0 = x_mid
        
        #Get error
        error = abs(f_mid)
     
    return x_mid, f_mid, it

%time compute_root(my_f, x0=3, x1=6, tol=1.0e-6, max_it=1000)
%time compute_root(my_f, x0=3, x1=6, tol=1.0e-6, max_it=1000)

CPU times: user 17 µs, sys: 34 µs, total: 51 µs
Wall time: 55.8 µs
CPU times: user 12 µs, sys: 24 µs, total: 36 µs
Wall time: 39.1 µs


(4.534070134162903, -7.047073751209609e-07, 23)